version: "2"
services:
  data:
    build: ./data
    volumes:
      - ../../:/data
      - ../logs:/logs
      - /var/lib/mysql
  db:
    image: mariadb
    volumes_from:
        - data
    environment:
      MYSQL_ROOT_PASSWORD: pass
  fpm:
    build: ./fpm
    volumes_from:
      - data
  nginx:
    build: ./nginx
    volumes_from:
      - data
    links:
      - fpm:fpm
    ports:
      - "80:80"
  composer:
    build: ./composer
    volumes_from:
      - data
  gulp:
    build: ./gulp
    volumes_from:
      - data
  npm:
    build: ./npm
    volumes_from:
      - data
