version: "2"
services:
  data:
    build: ./data
    volumes:
      - ../:/data
      - /var/lib/mysql
  db:
    image: mariadb
    volumes_from:
        - data
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db
  fpm:
    build: ./fpm
    volumes_from:
      - data
  nginx:
    build: ./nginx
    volumes_from:
      - data
    links:
      - fpm:fpm
    ports:
      - "80:80"
  composer:
    build: ./phpcli
    entrypoint: composer
    links:
      - db:db
    volumes_from:
      - data
  php:
    build: ./phpcli
    links:
      - db:db
    volumes_from:
      - data
    entrypoint: php
  gulp:
    build: ./gulp
    volumes_from:
      - data
  npm:
    build: ./npm
    volumes_from:
      - data
